apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: my-nodedb-app
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: nodedb-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nodedb-app
    spec:
      containers:
        - name: nodedb-app
          image: satyambrother/db-demo-app:02
        - name: mongodb
          image: mongo:latest
---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: nodedb-service
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    # here app name is same as pod name
    app: nodedb-app
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer
